### ISSUE TITLE
Details of Equation 4

### ISSUE THREAD

**Issue by valencebond** [bupt-ai-cz/IAST-ECCV2020#1]
Thanks for your code. Why p(c|x, w)/θ is used instead of only p(c|x, w), what`s the role played by θ？ And I can not find the corresponding code in this repo. I am unfamiliar with cross-domain semantic segmentation, so please forgive me if the question is too simple.

**Comment by super233** [comment]
Hi, thanks for your interest in our paper.

Equation 4 and equation 5 are borrowed from [CRST](http://arxiv.org/abs/1908.09822). Equation 4 has modeled the preprocess of pseudo-label generation with threshold ![theta^{(c)}](https://render.githubusercontent.com/render/math?math=\theta^{(c)}&mode=inline) when model parameter ![\mathbf{w}](https://render.githubusercontent.com/render/math?math=\mathbf{w}&mode=inline) is fixed, and the optimization is solved by equation 5.

I strongly recommend you to read [CRST](http://arxiv.org/abs/1908.09822), there is a detailed formula modeling for self-training and pseudo-label generation in **"3. Continuous class-balanced self-training"**.

If you have any other questions about our paper, please contact us without hesitation.
