### ISSUE TITLE
the size of GTA5 datasets

### ISSUE THREAD

**Issue by valencebond** [bupt-ai-cz/IAST-ECCV2020#2]
As far as I know, the size of the gta5 dataset is 24966. However, there are 24941 image-label pairs. The missing image ids are [ 2154,  2155,  2156,  2157,  2158,  4634,  4635,  4636,  4637, 7115,  7116,  7117,  7118,  7119,  9683,  9684,  9685,  9686, 9687,  9688, 12050, 12051, 12052, 12053, 12054]. Is there any reason? I appreciate any help you can provide.

**Comment by super233** [comment]
I'm sorry I can't provide the reason. The size of GTAV used in our paper is also 24941, which is less than the official size. For more details, please visit the [GTAV Official Page](https://download.visinf.tu-darmstadt.de/data/from_games/) and ask the official provider.
